import {
  ClipboardList,
  ListChecks,
  PenLine,
  BookOpen,
  Table2,
  StickyNote,
  BarChart3,
  Cloud,
  MessageCircleQuestion,
  Timer,
  Heart,
  Network,
  FileText,
  Link2,
} from "lucide-react";

export const MODULE_TYPES = [
  {
    type: "attendance",
    label: "Attendance",
    description: "Collect participant info — always the first module",
    Icon: ClipboardList,
    color: "text-teal-600",
    bg: "bg-teal-50",
    border: "border-teal-200",
    activeBg: "bg-teal-600",
  },
  {
    type: "quiz",
    label: "Quiz",
    description: "Multiple choice, short answer, or true/false questions",
    Icon: ListChecks,
    color: "text-violet-600",
    bg: "bg-violet-50",
    border: "border-violet-200",
    activeBg: "bg-violet-600",
  },
  {
    type: "whiteboard",
    label: "Whiteboard",
    description: "Free-draw collaborative canvas",
    Icon: PenLine,
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-200",
    activeBg: "bg-blue-600",
  },
  {
    type: "reflection",
    label: "Reflection Journal",
    description: "Prompted written response for participants",
    Icon: BookOpen,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    activeBg: "bg-emerald-600",
  },
  {
    type: "matrix",
    label: "Matrix",
    description: "Row × column grid for structured input",
    Icon: Table2,
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-200",
    activeBg: "bg-amber-600",
  },
  {
    type: "custom",
    label: "Sticky Notes",
    description: "Post-it style group brainstorm board",
    Icon: StickyNote,
    color: "text-pink-600",
    bg: "bg-pink-50",
    border: "border-pink-200",
    activeBg: "bg-pink-600",
  },
  {
    type: "poll",
    label: "Poll",
    description: "Live voting with real-time bar chart results",
    Icon: BarChart3,
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    activeBg: "bg-indigo-600",
  },
  {
    type: "wordcloud",
    label: "Word Cloud",
    description: "Participants submit words — see a live word cloud",
    Icon: Cloud,
    color: "text-cyan-600",
    bg: "bg-cyan-50",
    border: "border-cyan-200",
    activeBg: "bg-cyan-600",
  },
  {
    type: "qna",
    label: "Q&A Board",
    description: "Participants submit questions for the trainer",
    Icon: MessageCircleQuestion,
    color: "text-sky-600",
    bg: "bg-sky-50",
    border: "border-sky-200",
    activeBg: "bg-sky-600",
  },
  {
    type: "timer",
    label: "Timer",
    description: "Shared countdown timer for timed activities",
    Icon: Timer,
    color: "text-orange-600",
    bg: "bg-orange-50",
    border: "border-orange-200",
    activeBg: "bg-orange-600",
  },
  {
    type: "pulse",
    label: "Pulse Check",
    description: "Quick emoji mood check — gauge the room instantly",
    Icon: Heart,
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-200",
    activeBg: "bg-rose-600",
  },
  {
    type: "mapping",
    label: "Mapping",
    description: "Create focus areas with custom input fields",
    Icon: Network,
    color: "text-purple-600",
    bg: "bg-purple-50",
    border: "border-purple-200",
    activeBg: "bg-purple-600",
  },
  {
    type: "form",
    label: "Custom Form",
    description: "Build custom forms with various input types",
    Icon: FileText,
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    activeBg: "bg-indigo-600",
  },
  {
    type: "embed",
    label: "Embed / Link",
    description: "Embed an external link or content directly",
    Icon: Link2,
    color: "text-gray-600",
    bg: "bg-gray-50",
    border: "border-gray-200",
    activeBg: "bg-gray-600",
  },
] as const;

export type ModuleTypeDef = (typeof MODULE_TYPES)[number];

export function getModuleDef(type: string): ModuleTypeDef {
  return (MODULE_TYPES.find((m) => m.type === type) ?? MODULE_TYPES[0]) as ModuleTypeDef;
}
